# Generated by Django 3.2.25 on 2024-10-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=120, verbose_name='last_name')),
                ('tag', models.CharField(max_length=30, verbose_name='tag')),
                ('last_login', models.CharField(blank=True, max_length=30, null=True, verbose_name='login')),
                ('tag_id', models.IntegerField(null=True, verbose_name='id_tag')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users_images')),
                ('phone', models.CharField(max_length=10, null=True, verbose_name='phone')),
                ('battle_like', models.IntegerField(default=0)),
                ('admin_battle_like', models.IntegerField(default=0)),
                ('likes_users', models.TextField(null=True)),
                ('battle_like_activity', models.IntegerField(default=0)),
            ],
        ),
    ]
